### ISSUE TITLE
Getting a slew of errors on install. 

### ISSUE THREAD

**Issue by Traphowze11** [tegal1337/mapsdumper#1]
I cloned from git into my chosen install location, entered the directory, npm install. This is the output from node index.js

┌[parrot]─[13:55-06/08]─[/home/trap/toolset/osint/mapsdumper]
└╼trap$node index.js
/home/trap/toolset/osint/mapsdumper/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:129
        return this.eventsMap.get(event)?.length || 0;
                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/trap/toolset/osint/mapsdumper/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Browser.js:19:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by fdciabdul** [comment]
can you show me the nodejs version that you have?
